// 🤖 Renders the pricing page from copy-review/pricing/strings.json.
// Writes copy-review/pricing/preview/index.html (with data-copy bindings, for
// the review server) and src/pricing/index.html (the same page, bindings
// stripped, assets absolute). Re-run after an approved review is applied to
// strings.json; never edit the rendered files by hand.
import fs from "node:fs";
import path from "node:path";
const here = path.dirname(new URL(import.meta.url).pathname);
const root = path.resolve(here, "..", "..");
const strings = JSON.parse(fs.readFileSync(path.join(here, "strings.json"), "utf8"));
const S = Object.fromEntries(strings.map((s) => [s.id, s.text]));
// The five currency-control strings have their own review (approved
// 2026-10-01, copy-review/currency/result.json).
const currencyStrings = JSON.parse(fs.readFileSync(path.join(here, "..", "currency", "strings.json"), "utf8"));
for (const c of currencyStrings) S[c.id] = c.text;

// Every price, rate, band and default on the page comes from the platform's
// own price book (pricebook.json, generated by `go run ./cmd/pricebook-export`
// in carlos/platform and copied here; see pricebook.source.txt). Nothing
// commercial is typed into this script. The approved strings do carry a few
// figures of their own (the free plan's inclusions, the team minimum, the
// band percentages, the list of currencies); each is checked against the
// book below and the build stops on a difference.
const book = JSON.parse(fs.readFileSync(path.join(here, "pricebook.json"), "utf8"));
// A draft book is a draft: the console refuses to sell from it in live
// mode, and this page must not be published from it. The preview is always
// written for review; the deployable page is written only for an approved
// book, or when PRICEBOOK_ALLOW_DRAFT=1 says a draft is wanted (the review
// preview and the tests), and then it carries a marker that
// hack/check-pricebook.mjs refuses at `npm run check` unless the same
// variable is set.
const DRAFT = book.status !== "approved";
if (DRAFT && !process.env.PRICEBOOK_ALLOW_DRAFT) throw new Error(`the price book ${book.price_book} is ${book.status}, not approved: src/pricing/index.html is not written from it (set PRICEBOOK_ALLOW_DRAFT=1 for a review build)`);
const draftMarker = DRAFT ? `<!-- PRICE BOOK ${book.price_book} IS ${book.status.toUpperCase()}: not approved for sale, not for publication -->\n` : "";
const CURRENCIES = book.currencies.map((c) => c.code.toUpperCase());
const symbol = Object.fromEntries(book.currencies.map((c) => [c.code.toUpperCase(), c.symbol]));
const plansByKey = Object.fromEntries(book.plans.map((pl) => [pl.key, pl]));
// money renders minor units as the approved strings do: "€24", "€8.40",
// "$1,575" is not needed (no price reaches a thousand).
const money = (cur, minor) => {
  const major = Math.floor(minor / 100), rem = minor % 100;
  return symbol[cur] + major + (rem ? "." + String(rem).padStart(2, "0") : "");
};
// rate renders micro units exactly: at least three decimals, as the
// approved EUR rate strings are written ("€0.010 per hour"), and as many
// more as the figure needs ("$0.1272", "£0.0207"), never rounded. What the
// page shows is what the platform charges per unit.
const rate = (cur, micro) => {
  if (!Number.isInteger(micro) || micro < 0) throw new Error("not a micro amount: " + micro);
  const whole = Math.floor(micro / 1e6);
  let frac = String(micro % 1e6).padStart(6, "0");
  while (frac.length > 3 && frac.endsWith("0")) frac = frac.slice(0, -1);
  return symbol[cur] + whole + "." + frac;
};
// unitMinor is a plan's per-member annual price in a currency at a band.
const unitMinor = (plan, cur, band) => plansByKey[plan].annual_unit_minor[cur.toLowerCase()][band];
// values builds the data attribute the selector reads: the text for each
// currency, made by swapping the amount in the approved EUR string.
const values = (byCurrency) => esc(JSON.stringify(byCurrency));
// swapAmount puts an amount into an approved string in place of its euro
// amount, keeping every other word of the string as approved.
const swapAmount = (text, cur, amount) => {
  if (!/€[0-9][0-9.,]*/.test(text)) throw new Error("no euro amount in " + JSON.stringify(text));
  return text.replace(/€[0-9][0-9.,]*/, amount);
};
// The static text of every priced element is the book's default currency
// (USD) at band A: what a visitor with no script sees, and what the
// currency control shows selected before the script runs. The approved
// strings are the EUR texts; every other currency's text is the same
// words with the book's amount.
const BANDS = ["A", "B", "C", "D"];
const DEFAULT = book.default_currency.toUpperCase();
// priced renders an approved string whose euro amount varies by currency
// alone (an overage rate, the floor, the free plan's price): every
// currency's text in data-currency-values for the selector.
const priced = (id, amountFor, tag = "span", cls = "") => {
  if (!(id in S)) throw new Error("missing string " + id);
  const by = Object.fromEntries(CURRENCIES.map((cur) => [cur, swapAmount(S[id], cur, amountFor(cur))]));
  if (by.EUR !== S[id]) throw new Error("the book's EUR amount differs from the approved string " + id + ": " + by.EUR + " vs " + S[id]);
  return `<${tag}${cls ? ` class="${cls}"` : ""} data-copy="${id}" data-currency-values="${values(by)}">${esc(by[DEFAULT])}</${tag}>`;
};
// banded renders a string whose amount varies by band and currency (a
// paid plan's price line): every band's texts, each by currency, in
// data-band-values. The selector picks the band from the billing country.
const banded = (id, textFor, tag = "span", cls = "") => {
  if (!(id in S)) throw new Error("missing string " + id);
  const by = Object.fromEntries(BANDS.map((band) => [band, Object.fromEntries(CURRENCIES.map((cur) => [cur, textFor(band, cur)]))]));
  if (by.A.EUR !== S[id]) throw new Error("the book's band A EUR amount differs from the approved string " + id + ": " + by.A.EUR + " vs " + S[id]);
  return `<${tag}${cls ? ` class="${cls}"` : ""} data-copy="${id}" data-band-values="${values(by)}">${esc(by.A[DEFAULT])}</${tag}>`;
};
const bandCell = (plan, band) => `<td data-currency-values="${values(Object.fromEntries(CURRENCIES.map((cur) => [cur, money(cur, unitMinor(plan, cur, band))])))}">${esc(money(DEFAULT, unitMinor(plan, DEFAULT, band)))}</td>`;
// A band-scaled plan's per-member inclusions at a band are the plan's
// figure times the band factor, divided by 10000 and rounded down: the
// platform's own pooling rule (public-pricebook.json), at one member. The
// approved string is band A's; the other bands' texts are the same words
// with that band's figure, in data-band-values. A figure that is not exact
// to three decimals stops the build rather than rounding on the page.
const allowanceOf = {
  personal: { i2: "awake_seconds", i3: "storage_byte_months", i4: "transfer_bytes" },
  community: { i1: "awake_seconds", i2: "storage_byte_months", i3: "transfer_bytes" },
  business: { i1: "awake_seconds", i2: "storage_byte_months", i3: "transfer_bytes", i4: "writes" },
};
const figure = (resource, amount) => {
  const n = resource === "awake_seconds" ? amount / 3600 : resource === "writes" ? amount : amount / 1e9;
  const text = n.toFixed(3).replace(/\.?0+$/, "");
  if (Number(text) !== n) throw new Error("not an exact figure: " + resource + " " + amount);
  const [int, frac] = text.split(".");
  return int.replace(/\B(?=(\d{3})+(?!\d))/g, ",") + (frac ? "." + frac : "");
};
const swapFigure = (text, fig) => {
  if (!/^[0-9][0-9,]*(\.[0-9]+)?/.test(text)) throw new Error("no leading figure in " + JSON.stringify(text));
  return text.replace(/^[0-9][0-9,]*(\.[0-9]+)?/, fig);
};
const allowanceLi = (p, i) => {
  const id = `plan.${p}.${i}`, plan = plansByKey[p], resource = (allowanceOf[p] || {})[i];
  if (!resource || !plan.band_scaled) return li(id);
  const by = Object.fromEntries(BANDS.map((band) => [band, swapFigure(S[id], figure(resource, Math.floor(plan.resources_per_member[resource] * book.band_factors_bps[band] / 10000)))]));
  if (by.A !== S[id]) throw new Error("band A's figure differs from the approved string " + id + ": " + by.A + " vs " + S[id]);
  return `        <li data-copy="${id}" data-band-values="${values(by)}">${esc(S[id])}</li>`;
};
const overageRate = (meter) => (cur) => rate(cur, book.overage[cur.toLowerCase()][meter]);
const defaultCurrencyFor = (iso2) => (book.country_currency[iso2] || book.default_currency).toUpperCase();
const esc = (t) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const t = (id, tag = "span", cls = "") => {
  if (!(id in S)) throw new Error("missing string " + id);
  return `<${tag}${cls ? ` class="${cls}"` : ""} data-copy="${id}">${esc(S[id])}</${tag}>`;
};
const li = (id) => `        <li data-copy="${id}">${esc(S[id])}</li>`;
// The countries are the book's (country_band: every country the console
// sells to, with its band); countries.json supplies the names only, and a
// country the book sells to with no name stops the build.
const countries = JSON.parse(fs.readFileSync(path.join(here, "countries.json"), "utf8"));
const names = new Map((countries.countries || countries.records || []).map((r) => [r.iso2, r.name]));
const recs = Object.entries(book.country_band).map(([iso2, band]) => {
  if (!names.has(iso2)) throw new Error("the book sells to " + iso2 + ", which countries.json does not name");
  return { iso2, band, name: names.get(iso2) };
}).sort((a, b) => a.name.localeCompare(b.name));
const byBand = { A: [], B: [], C: [], D: [] };
for (const r of recs) byBand[r.band].push(r.name);

// The figures the approved strings carry that are the book's to decide.
const must = (id, text, what) => { if (!S[id].includes(text)) throw new Error(`${id} (${JSON.stringify(S[id])}) does not carry ${what} ${JSON.stringify(text)} from the book`); };
for (const p of ["community", "business"]) must(`plan.${p}.min`, String(plansByKey[p].min_quantity), "the minimum");
for (const [b, id] of [["B", "bands.b"], ["C", "bands.c"], ["D", "bands.d"]]) must(id, (book.band_factors_bps[b] / 100) + "%", "the band percentage");
if (book.band_factors_bps.A !== 10000) throw new Error("band A is not the full price");
const free = plansByKey.free.resources_per_member;
must("plan.free.i3", String(free.awake_seconds / 3600) + " awake hours", "the free plan's awake hours");
must("plan.free.i4", String(free.storage_byte_months / 1e6) + " MB", "the free plan's storage");
must("plan.free.i5", String(free.transfer_bytes / 1e9) + " GB", "the free plan's transfer");
must("currency.explanation", CURRENCIES.slice(0, -1).join(", ") + " or " + CURRENCIES[CURRENCIES.length - 1], "the currencies sold");
// The per-member figures shown are exact shares of what the console pools:
// for every band-scaled plan, figure x factor is whole in base units, at one
// member and at the plan's minimum. If a future book breaks that, the page
// must say the pooled figure instead, and this stops the build until it does.
for (const pl of book.plans) {
  if (!pl.band_scaled) continue;
  for (const [resource, f] of Object.entries(pl.resources_per_member)) for (const [b, bps] of Object.entries(book.band_factors_bps)) {
    if ((f * bps) % 10000 !== 0 || (f * pl.min_quantity * bps) % 10000 !== 0) throw new Error(`${pl.key} ${resource} at band ${b} is not an exact per-member share`);
  }
}
const bandList = Object.entries(byBand).map(([b, names]) =>
  `        <div class="band-col"><h3>Band ${b}</h3><p>${names.map(esc).join(", ")}</p></div>`).join("\n");

// The plan cards, grouped as the approved review laid them out: a team
// plan's per-member inclusions sit under the shared "Each member adds"
// heading (plan.team.allowances), and what Business adds beyond them
// (continuous replication, priority support) is its own list.
const planCardLists = {
  free: { plain: ["i1", "i2", "i3", "i4", "i5", "i6", "i7", "i8"] },
  personal: { plain: ["i1", "i2", "i3", "i4"] },
  community: { allowances: ["i1", "i2", "i3"] },
  business: { allowances: ["i1", "i2", "i3", "i4"], features: ["i5", "i6"] },
};
const priceLine = (p) => {
  const id = `plan.${p}.price`;
  if (p === "free") return priced(id, (cur) => money(cur, unitMinor(p, cur, "A")));
  return banded(id, (band, cur) => swapAmount(S[id], cur, money(cur, unitMinor(p, cur, band))));
};
const card = (p, featured) => {
  const lists = planCardLists[p];
  const items = (ids) => ids.map((i) => allowanceLi(p, i)).join("\n");
  const seen = new Set([...(lists.plain || []), ...(lists.allowances || []), ...(lists.features || [])].map((i) => `plan.${p}.${i}`));
  for (const k of Object.keys(S).filter((k) => k.startsWith(`plan.${p}.i`))) if (!seen.has(k)) throw new Error("unplaced string " + k);
  return `      <article class="plan${featured ? " featured" : ""}">
        ${t(`plan.${p}.name`, "h3")}
        <p class="price">${priceLine(p)}</p>
${S[`plan.${p}.min`] ? `        <p class="min">${t(`plan.${p}.min`)}</p>\n` : ""}        <p class="for">${t(`plan.${p}.for`)}</p>
${lists.plain ? `        <ul>\n${items(lists.plain)}\n        </ul>\n` : ""}${lists.allowances ? `        <p class="allowance-heading" data-copy="plan.team.allowances">${esc(S["plan.team.allowances"])}</p>\n        <ul class="allowances">\n${items(lists.allowances)}\n        </ul>\n` : ""}${lists.features ? `        <ul class="plan-features">\n${items(lists.features)}\n        </ul>\n` : ""}        <a class="btn ${featured ? "btn-primary" : "btn-quiet"}" href="https://console.carloku.com/?plan=${p}" data-pricing-signup data-copy="plan.${p}.cta">${esc(S[`plan.${p}.cta`])}</a>
      </article>`;
};

// The currency and billing-country controls, in the approved words. The
// country list is every country the book sells to, with its default
// currency and its band; the selector script (site.js) applies the
// currency to every priced string on the page, the country's band to every
// banded one, and both to the signup links. No price is charged from this
// page: checkout prices from the same book, for the country the buyer
// gives there.
const bandOf = (iso2) => {
  if (!BANDS.includes(book.country_band[iso2])) throw new Error("the book has no band for " + iso2);
  return book.country_band[iso2];
};
const countryOptions = recs.map((r) => `<option value="${r.iso2}" data-currency="${defaultCurrencyFor(r.iso2)}" data-band="${bandOf(r.iso2)}">${esc(r.name)}</option>`).join("");
const controls = `  <section class="pricing-controls">
    <div class="wrap narrow">
      <form class="currency-form" onsubmit="return false">
        <div class="control">
          <label for="pricing-currency" data-copy="currency.label">${esc(S["currency.label"])}</label>
          <select id="pricing-currency" data-pricing-currency>${CURRENCIES.map((c) => `<option value="${c}">${c}</option>`).join("")}</select>
          <p class="control-note" data-copy="currency.explanation">${esc(S["currency.explanation"])}</p>
        </div>
        <div class="control">
          <label for="pricing-country" data-copy="country.label">${esc(S["country.label"])}</label>
          <select id="pricing-country" data-pricing-country><option value=""></option>${countryOptions}</select>
          <p class="control-note" data-copy="country.explanation">${esc(S["country.explanation"])}</p>
        </div>
      </form>
      <p class="control-note fixed" data-copy="currency.fixed">${esc(S["currency.fixed"])}</p>
    </div>
  </section>`;

const page = `${draftMarker}<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title data-copy="meta.title">${esc(S["meta.title"])}</title>
<meta name="description" content="🤖 ${esc(S["meta.description"])}">
<meta property="og:title" content="${esc(S["meta.title"])}">
<meta property="og:description" content="${esc(S["meta.description"])}">
<meta property="og:type" content="website">
<meta property="og:url" content="https://carloku.com/pricing/">
<meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0e0c13" media="(prefers-color-scheme: dark)">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="preload" href="/fonts/Geist-Variable.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/fonts/GeistMono-Variable.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/site.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="site-head">
  <div class="wrap">
    <a class="brand" href="/"><svg class="mark" viewBox="0 0 64 64" aria-hidden="true"><rect width="64" height="64" rx="14" fill="#5b3e96"/><circle cx="30" cy="32" r="17" fill="none" stroke="#ffffff" stroke-width="8" stroke-linecap="round" stroke-dasharray="88.8 18" stroke-dashoffset="-9"/><circle cx="51" cy="44" r="5" fill="#c9b2f7"/></svg>Carloku</a>
    <nav aria-label="Site">
      <a href="/#workflow">How it works</a>
      <a href="/#open">Open source</a>
      <a href="/pricing/" aria-current="page" data-copy="nav.pricing">${esc(S["nav.pricing"])}</a>
      <a href="/get-started/">Get started</a>
    </nav>
    <a class="head-cta" href="https://console.carloku.com">Dashboard</a>
  </div>
</header>
<main id="main">
  <div class="page-hero">
    <div class="wrap narrow">
      <h1><span data-copy="hero.title">${esc(S["hero.title"])}</span><span class="dot">.</span></h1>
      <p class="lede" data-copy="hero.lede">${esc(S["hero.lede"])}</p>
      <p class="hero-note" data-copy="hero.new">${esc(S["hero.new"])}</p>
    </div>
  </div>
${controls}
  <section class="plans-section">
    <div class="wrap">
      ${t("plans.heading", "h2")}
      <div class="plans">
${card("free", false)}
${card("personal", true)}
${card("community", false)}
${card("business", false)}
      </div>
      <p class="plans-note" data-copy="plans.note">${esc(S["plans.note"])}</p>
    </div>
  </section>
  <section class="tint">
    <div class="wrap narrow prose">
      ${t("member.heading", "h2")}
      <p data-copy="member.p1">${esc(S["member.p1"])}</p>
      <p data-copy="member.p2">${esc(S["member.p2"])}</p>
    </div>
  </section>
  <section>
    <div class="wrap narrow prose">
      ${t("bands.heading", "h2")}
      <p data-copy="bands.p1">${esc(S["bands.p1"])}</p>
      <ul>
${["a", "b", "c", "d"].map((b) => li("bands." + b)).join("\n")}
      </ul>
      <table class="price-table">
        <thead><tr><th scope="col"><span class="visually-hidden">Plan</span></th><th scope="col">A</th><th scope="col">B</th><th scope="col">C</th><th scope="col">D</th></tr></thead>
        <tbody>
${["personal", "community", "business"].map((pl) => `          <tr><th scope="row" data-copy="bands.table.${pl}">${esc(S[`bands.table.${pl}`])}</th>${["A", "B", "C", "D"].map((b) => bandCell(pl, b)).join("")}</tr>`).join("\n")}
        </tbody>
      </table>
      <p data-copy="bands.p2">${esc(S["bands.p2"])}</p>
      <p data-copy="bands.p3">${esc(S["bands.p3"])}</p>
      <details class="bands-all">
        <summary data-copy="bands.list.summary">${esc(S["bands.list.summary"])}</summary>
${bandList}
      </details>
    </div>
  </section>
  <section class="tint">
    <div class="wrap narrow prose">
      ${t("over.heading", "h2")}
      <p data-copy="over.p1">${esc(S["over.p1"])}</p>
      <table class="price-table rates">
        <tbody>
          <tr><th scope="row" data-copy="over.table.awake">${esc(S["over.table.awake"])}</th>${priced("over.rate.awake", overageRate("awake_hour_micro"), "td")}</tr>
          <tr><th scope="row" data-copy="over.table.storage">${esc(S["over.table.storage"])}</th>${priced("over.rate.storage", overageRate("storage_gb_month_micro"), "td")}</tr>
          <tr><th scope="row" data-copy="over.table.transfer">${esc(S["over.table.transfer"])}</th>${priced("over.rate.transfer", overageRate("transfer_gb_micro"), "td")}</tr>
          <tr><th scope="row" data-copy="over.table.writes">${esc(S["over.table.writes"])}</th>${priced("over.rate.writes", overageRate("writes_1000_micro"), "td")}</tr>
        </tbody>
      </table>
      ${priced("over.p2", (cur) => money(cur, book.overage[cur.toLowerCase()].invoice_floor_micro / 10000), "p")}
      <p data-copy="over.p3">${esc(S["over.p3"])}</p>
    </div>
  </section>
  <section class="band">
    <div class="wrap">
      ${t("half.heading", "h2")}
      <p data-copy="half.p1">${esc(S["half.p1"])}</p>
    </div>
  </section>
  <section>
    <div class="wrap narrow prose">
      ${t("promise.heading", "h2")}
      <p data-copy="promise.p1">${esc(S["promise.p1"])}</p>
      ${t("pay.heading", "h2")}
      <p data-copy="pay.p1">${esc(S["pay.p1"])}</p>
      <p data-copy="pay.p2">${esc(S["pay.p2"])}</p>
      <p data-copy="pay.p3">${esc(S["pay.p3"])}</p>
      <p data-copy="pay.p4">${esc(S["pay.p4"])}</p>
    </div>
  </section>
  <section class="close-cta">
    <div class="wrap">
      <h2><span data-copy="start.heading">${esc(S["start.heading"])}</span><span class="dot">.</span></h2>
      <p data-copy="start.p1">${esc(S["start.p1"])}</p>
      <div class="cta">
        <a class="btn btn-primary" href="https://console.carloku.com" data-pricing-signup data-copy="start.cta.console">${esc(S["start.cta.console"])}</a>
        <a class="btn btn-quiet" href="/get-started/" data-copy="start.cta.guide">${esc(S["start.cta.guide"])}</a>
      </div>
    </div>
  </section>
</main>
<footer>
  <div class="wrap">
    <p>🤖 Written by an LLM (Claude), on the ideas, instruction, and editing of humans.
    AI-written text here is always marked and always disclosed; see
    <a href="https://11factor.org/#x">factor X</a>.</p>
    <p><a href="/">← carloku.com</a> · <a href="https://github.com/carlosframework/carloku">Source on GitHub</a>.</p>
  </div>
</footer>
<script src="/site.js" defer></script>
</body>
</html>
`;
fs.mkdirSync(path.join(root, "src", "pricing"), { recursive: true });
fs.writeFileSync(path.join(root, "src", "pricing", "index.html"), page.replace(/ data-copy(?:-title)?="[^"]*"/g, ""));
const prev = path.join(here, "preview");
fs.mkdirSync(path.join(prev, "fonts"), { recursive: true });
for (const f of ["site.css", "favicon.svg"]) fs.copyFileSync(path.join(root, "src", f), path.join(prev, f));
for (const f of fs.readdirSync(path.join(root, "src", "fonts"))) fs.copyFileSync(path.join(root, "src", "fonts", f), path.join(prev, "fonts", f));
for (const f of ["site.js"]) fs.copyFileSync(path.join(root, "src", f), path.join(prev, f));
let previewHtml = page
  .replace(/href="\/site\.css"/, 'href="site.css"')
  .replace(/<script src="\/site\.js" defer><\/script>/, '<script src="site.js" defer></script>')
  .replace(/href="\/fonts\//g, 'href="fonts/"'.slice(0, -1))
  .replace(/href="\/favicon\.svg"/, 'href="favicon.svg"')
  ;
fs.writeFileSync(path.join(prev, "index.html"), previewHtml);
console.log("wrote src/pricing/index.html and copy-review/pricing/preview/index.html", strings.length, "strings");
